DBS/odovzdanie3/source/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :cities
  resources :areas, only: [:show, :create, :destroy, :update]
  resources :comments, only: [:create, :destroy]
  resources :statistics, only: [:index]

end

DBS/odovzdanie3/source/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Aplikácia Venčoviská
    od <a href="http://kovko.yweb.sk/">Michala Kováčika</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "O nás", about_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>
    </ul>
  </nav>
</footer>

DBS/odovzdanie3/source/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Venčoviská", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Domov", '/' %></li>
        <li><%= link_to "Mesta", cities_path %></li>
        <li><%= link_to "Statistika", statistics_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Použivatelia", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user().name.partition(' ').first %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profil", current_user %></li>
                <li><%= link_to "Nastavenia", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Odhlásiť", logout_path, method: "delete" %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Prihlásiť sa", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

DBS/odovzdanie3/source/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">

  <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>"><p class="center"><%= message %></p></div>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>