DBS/odovzdanie2/source/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :cities
  resources :areas, only: [:show, :create, :destroy, :update]
  resources :comments, only: [:create, :destroy]
  resources :statistics, only: [:index]

end

DBS/odovzdanie2/source/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

DBS/odovzdanie2/source/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

DBS/odovzdanie2/source/app/views/static_pages/about.html.erb
<%= provide(:title, "O nás")%>
<h1>About vencoviska</h1>
<p>this is about page</p>

DBS/odovzdanie2/source/app/views/static_pages/contact.html.erb
<%= provide :title, "Kontakt" %>
<h1>Kontakt</h1>
<p>Kontaktný formulár</p>

DBS/odovzdanie2/source/app/views/static_pages/help.html.erb
<%= provide(:title, "Nápoveda")%>
<h1>Help page</h1>
<p>toto je stranka helpu na vencoviskach</p>

DBS/odovzdanie2/source/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Vitajte vo venčoviskách</h1>

  <h2>Toto je domovská stránka</h2>

  <%= link_to("Zaregistrujte sa teraz!", signup_path, class: "btn btn-lg btn-primary") unless logged_in? %>
  <%= link_to("Zobraziť zoznam miest", cities_path, class: "btn btn-lg btn-primary") %>
</div>